### GET ALL
GET http://localhost:5000/api/wilder

### DELETE BY ID
DELETE http://localhost:3000/api/wilder/28

### CREATE WILDER
POST http://localhost:5000/api/wilder
 Content-Type: application/json

{
    "name" : "Rosie Beaumont",
    "email" : "rosie@gmail.com"
}
 
### UPDATE WILDER
PUT http://localhost:3000/api/wilder/1
 Content-Type: application/json

{
    // "email" : "john@gmail.com"
}


### GET ALL
GET http://localhost:3000/api/skills

### DELETE BY ID
DELETE http://localhost:3000/api/skill/2

### CREATE SKILL
POST http://localhost:3000/api/skill
 Content-Type: application/json

{
    "name" : "Node"
}
 
### UPDATE SKILL
PUT http://localhost:3000/api/skill/27
 Content-Type: application/json

 { 
    "name" : "html"
 }

### ADD SKILL TO WILDER
POST http://localhost:3000/api/addSkill
 Content-Type: application/json

{
    "wilderName": "Bojack Horseman",
    "skillName": "HTML"
}